pdf/pdf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from superadmin.views import*
from django.views.static import serve 


urlpatterns = [
    
    path('login/', login_page, name='login'),
    path('', login_page),
    path('register/', register_page, name='register_page'),
    path('logout/', logout_page, name='logout'),
    path('adminn/', admin.site.urls),
    path('admin/',  include(('superadmin.urls', 'superadmin'), namespace='superadmin')),
    path('', include(('user.urls', 'user'), namespace='user')),
   
    
]
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pdf/user/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


'''
    This is url file here three url 
    one for dashboard and another one select courses
    third for view your timetable.
 
 '''
urlpatterns = [
     path('dashboard/', get_index_page, name='dashboard'), 
     path('select-courses/', select_courses, name='select_courses'),
     path('show-timetable/', show_timetable, name='show_timetable'),     
]

pdf/user/models.py
from django.db import models
from django.contrib.auth.models import User

pdf/user/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import render ,redirect
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from .serializers import  UserSerializerForTimeTable
from rest_framework.response import Response
from rest_framework import status
from django.contrib.auth.decorators import login_required

from django.db.models.functions import ExtractWeekDay
from django.db.models import Func
import datetime
from django.contrib.auth.models import User
from superadmin.models import  Allcourse, Allstudent, Constraint
import os
from  datetime import time
from itertools import groupby
from operator import itemgetter
from collections import OrderedDict
from datetime import datetime, time
import pdb

# Create your views here.
'''
    This function take three argument 
    request course for course object and constraint object 
   
    check_already_constraint
 
'''
def check_already_constraint(request,cours,constraint_obj):

    
    if cours:
        #orted_time_slots = sorted(course_list, key=lambda slot: slot['start_time'])

        if len(constraint_obj) >=2:
            print("list",constraint_obj)
            course_list = list(constraint_obj)
            time_differences = []
           
            first=constraint_obj.first()
            last = constraint_obj.last()
            if cours.start_time >=last.end_time:
                return True
            elif cours.end_time<=first.start_time:
                return True
                


            for constraint1, constraint2 in zip(course_list, course_list[1:]):   
                   
                    if constraint1.end_time <= cours.start_time <= constraint2.start_time and  constraint1.end_time <= cours.end_time <= constraint2.start_time:
                        return True
                      
                    # elif constraint1.start_time >= cours.end_time <= constraint1.end_time:
                    #     return True
                    
                    # elif len(constraint_obj) ==2:
                    #     if constraint2.end_time <= cours.start_time >= constraint2.start_time:
                    #         return True

                    
                    

            
            return False      

        elif len(constraint_obj) == 1:
            for const in constraint_obj:
               
                if const.start_time <= cours.start_time <= const.end_time or const.start_time <= cours.end_time <= const.end_time:
                    return False
                else:
                    return True
  
   

'''
    This function take five argument  and check one constraint with
    already existing constraint and courses.if any available slot for 
    constraint then constraint object is created. 
 
'''
def check_contt(request,name,day,start_time,end_time):
    days = day[:3]
    start_timee_2 = time.fromisoformat(start_time)
    end_timee_2 = time.fromisoformat(end_time)   
    allstudent=Allstudent.objects.filter(user=request.user) 
    student = Allcourse.objects.filter(allstudent__user=request.user,day=days)
    student_list=list(student)
    sorted_list = sorted(student_list, key=lambda x: x.start_time)
    first=sorted_list[0]
    last=sorted_list[len(sorted_list)-1]
    if start_timee_2 >=last.end_time:
        already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
        if already_cons:
            return False
        else:
            Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
            return True
    elif end_timee_2<=first.start_time:
        already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
        if already_cons:
            return False
        else:
            Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
            return True
    
    for constraint1, constraint2 in zip(sorted_list, sorted_list[1:]):   
            
            if constraint1.end_time <= start_timee_2 <= constraint2.start_time and  constraint1.end_time <= end_timee_2 <= constraint2.start_time:
                already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                if already_cons:
                    return False
                else:
                    Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                    return True

    return False
def check_contt_two(request,name,day,start_time,end_time):
    days = day[:3]
    start_timee_2 = time.fromisoformat(start_time)
    end_timee_2 = time.fromisoformat(end_time)   
    constraint_obj=Constraint.objects.filter(user=request.user,day=day)
    student_list=list(constraint_obj)
    sorted_list = sorted(student_list, key=lambda x: x.start_time)
    first=sorted_list[0]
    last=sorted_list[len(sorted_list)-1]
    if start_timee_2 >=last.end_time:
        already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
        if already_cons:
            return False
        else:
            Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
            return True
    elif end_timee_2<=first.start_time:
        already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
        if already_cons:
            return False
        else:
            Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
            return True
    
    for constraint1, constraint2 in zip(sorted_list, sorted_list[1:]):   
            
            if constraint1.end_time <= start_timee_2 <= constraint2.start_time and  constraint1.end_time <= end_timee_2 <= constraint2.start_time:
                already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                if already_cons:
                    return False
                else:
                    Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                    return True

    return False


def check_constraint_to_add(request,name,day,start_time,end_time):
    days = day[:3]
    start_timee_2 = time.fromisoformat(start_time)
    end_timee_2 = time.fromisoformat(end_time)
  
   
    constraint_obj=Constraint.objects.filter(user=request.user,day=day)
    allstudent=Allstudent.objects.filter(user=request.user) 
    student = Allcourse.objects.filter(allstudent__user=request.user,day=days)
    if not constraint_obj and not student:
        already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
        if already_cons:
            return False
        else:
            Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
            return True
    
    elif  constraint_obj and student:
        student_list=list(student)
        cons_list =list(constraint_obj)
        appended_list = student_list + cons_list
        sorted_list = sorted(appended_list, key=lambda x: x.start_time)
        first=sorted_list[0]
        last=sorted_list[len(sorted_list)-1]
        start_timee_2 = time.fromisoformat(start_time)
        end_timee_2 = time.fromisoformat(end_time)
        if start_timee_2 >=last.end_time:
            already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
            if already_cons:
                return False
            else:
                Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                return True
        elif end_timee_2<=first.start_time:
            already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
            if already_cons:
                return False
            else:
                Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                return True
        
        for constraint1, constraint2 in zip(sorted_list, sorted_list[1:]):   
                
                if constraint1.end_time <= start_timee_2 <= constraint2.start_time and  constraint1.end_time <= end_timee_2 <= constraint2.start_time:
                    already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                    if already_cons:
                        return False
                    else:
                        Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                        return True
    
        return False
    else:
        if student:
            student_list=list(student)
            sorted_list = sorted(student_list, key=lambda x: x.start_time)
            if len(student_list) == 1:
                first=sorted_list[0]
                if end_timee_2<=first.start_time or first.end_time <=start_timee_2:
                    already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                    if already_cons:
                        return False
                    else:
                        Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                        return True
            else:
                check_contt(request,name,day,start_time,end_time)

pdf/user/templates/user/index.html
{% extends 'user/layout/base.html' %}
{% load tz %}

{% block content %}






<div class="container">
  {% if const_errors %}
  <div><p style="color: red; font-size: 15px; text-align: center;">{{const_errors}}</p></div>

  {% endif %}
  {% if errors %}
  <div><p style="color: red; font-size: 15px; text-align: center;">{{errors}}</p></div>
  {% endif%}

 

  <div class=" text-center mt-5 ">
    <h1>Available Course</h1>
  </div>
  <div class="row">
    <div class="col-lg-7 mx-auto">

      <div class="card mt-2 mx-auto p-4 bg-light" style=" height:250px;
      overflow-y: scroll;">

        <div class="card-body bg-light">
          <form method="POST" action="{% url 'user:select_courses' %}">
            {% csrf_token %}

            <div class="container">

              {% for cour in cource %}

              <div class="form-check">

                <input class="form-check-input" type="checkbox" name="courses" value="{{ cour.name }}" autocomplete="off">
                <label class="form-check-label" for="course{{ cour.id }}" style="font-size: 20px;
                margin-bottom: 10px;
                margin-left: 20px;">{{ cour.name }}</label>

              </div>


              {% endfor %}
            </div>


        </div>

      </div>

    </div>

  </div>



  <!-- new Row -->
  <div class="row ">
    <div class="col-lg-7 mx-auto">

      <div class="card mt-3 mx-auto p-4 bg-light">

        <div class="card-body bg-light">


          <div class="container">




            <div class="controls">

              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="daySelect">How many constraint do you add:</label>
                    <select class="form-control" id="conSelect" name="dayconst">
                      <option value="1">1</option>
                      <option value="2">2</option>

                    </select>
                  </div>
                </div>
                <div class="col-md-6">

                  <button class="btn btn-primary" type="button" style=" margin-top: 25px;"
                    id="constraint_button">submit</button>

                </div>

              </div>





            </div>
          </div>
        </div>
      </div>
    </div>
  </div>





  <!-- End Row -->
  <!-- start row -->
  <div class="row" >
    <div class="col-lg-7 mx-auto">

      <div class="card mt-3 mx-auto p-4 bg-light" id="constraint_one" style="display: none;">

        <div class="card-body bg-light">


          <div class="container">




            <div class="controls">

              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="daySelect"> Select Day:</label>
                    <select class="form-control" id="daySelect" name="day" autocomplete="off">
                      <option value="" selected>Choose an option</option>
                      <option value="sunday">Sunday</option>
                      <option value="monday">Monday</option>
                      <option value="tuesday">Tuesday</option>
                      <option value="wednesday">Wednesday</option>
                      <option value="thursday">Thursday</option>
                      <option value="friday">Friday</option>
                     
                    </select>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="form_lastname">Contraints Name*</label>
                    <input type="text" name="constraint" class="form-control" autocomplete="off" placeholder="enter Constraints Name">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="form_email">Start Time*</label>
                    <input type="time" name="start_time" class="form-control" autocomplete="off" placeholder="enter Constraints Name">

                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="form_need">End Time*</label>
                    <input type="time" name="end_time" class="form-control" autocomplete="off" placeholder="enter Constraints Name">
                  </div>
                </div>
               

                 









               
               

              </div>





            </div>
          </div>
        </div>
      </div>
    </div>
  </div>




  <!-- end row -->
  <!-- start constrain two -->



  <div class="row"  >
    <div class="col-lg-7 mx-auto" >

      <div class="card mt-3 mx-auto p-4 bg-light" id="constraint_two" style="display: none;">

        <div class="card-body bg-light">


          <div class="container">




            <div class="controls">

              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="daySelect"> Select Day:</label>
                    <select class="form-control" id="daySelect" autocomplete="off" name="day_2">
                      <option value="" selected>Choose an option</option>
                      <option value="sunday">Sunday</option>
                      <option value="monday">Monday</option>
                      <option value="tuesday">Tuesday</option>
                      <option value="wednesday">Wednesday</option>
                      <option value="thursday">Thursday</option>
                      <option value="friday">Friday</option>
                      
                     
                    </select>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="form_lastname">Contraints Name*</label>
                    <input type="text" name="constraint_2" autocomplete="off" class="form-control" placeholder="enter Constraints Name">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="form_email">Start Time*</label>
                    <input type="time" name="start_time_2" autocomplete="off" class="form-control" placeholder="enter Constraints Name">

                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="form_need">End Time*</label>
                    <input type="time" name="end_time_2"  autocomplete="off" class="form-control" placeholder="enter Constraints Name">
                  </div>
                </div>
               

                 









               
               

              </div>





            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<!-- end constraint -->


<!-- start last row -->

 <div class="row">
  <div class="col-5"></div>
  <div class="col-5">
   <div>
    <button type="submit" class="btn-primary" class="form-control"  style="padding: 10px 50px; background-color: cadetblue;">Submit</button>
   </div>
  </div>
  <div class="col-2"></div>
</div>

  

      


    </div>
    </form>
    <!-- /.row-->













 












    










 




  {% endblock %}

  {% block javascript %}
  <script type="text/javascript">


    const button = document.getElementById('constraint_button');

    // Define the event handler function
    function handleClick() {
      console.log('Button clicked!');
      const selectElement = document.getElementById("conSelect");

      // Get the selected value
      const selectedValue = selectElement.value;
      if (selectedValue == 1){
        $('#constraint_one').css('display', 'block');

      }
      if (selectedValue == 2){
        $('#constraint_one').css('display', 'block');
        $('#constraint_two').css('display', 'block');

      }
   
     

     

     
      console.log("Selected value: " + selectedValue);
    }

    // Add event listener for click event
    button.addEventListener('click', handleClick);



  </script>


  {% endblock %}

pdf/user/templates/user/timetable.html
{% extends 'user/layout/base.html' %}





{% block style %}





{% endblock %}


{% block content %}




  




<div class="container">


  <div class="row">

    <div class="col-3"> <h4 class="text-uppercase" style="text-align:center;margin-left: 2px;;">Days</h4></div>
    <div class="col-1"></div>
    <div class="col-5"> <h4 class="text-uppercase" style="text-align:center;margin-left: 2px;;">Courses With times</h4></div>
  </div>
  <div class="timetable-img text-center">
      <img src="img/content/timetable.png" alt="">
  </div>
  
  </div>
  <div class="table-responsive">
      <table class="table table-bordered text-center">
          <thead>
              <tr class="bg-light-gray">
                  <!-- <th class="text-uppercase">Days
                  </th>
                  <th class="text-uppercase">Courses With Time</th> -->
                  <!-- <th class="text-uppercase">Monday</th>
                  <th class="text-uppercase">Tuesday</th>
                  <th class="text-uppercase">Wednesday</th>
                  <th class="text-uppercase">Thursday</th>
                  <th class="text-uppercase">Friday</th>
                  <th class="text-uppercase">Saturday</th> -->
              </tr>
          </thead>
          <tbody>
            {% for day, items in data.items %}

            <tr>
              {% if day == 1%}
              <th class="text-uppercase align-middle">Sunday</th>
              {% endif %}
              {% if day == 2%}
              <th class="text-uppercase align-middle">Monday</th>
              {% endif %}
              {% if day == 3%}
              <th class="text-uppercase align-middle">Tuesday</th>
              {% endif %}
              {% if day == 4%}
              <th class="text-uppercase align-middle">Wednesday</th>
              {% endif %}
              {% if day == 5%}
              <th class="text-uppercase align-middle">Thursday</th>
              {% endif %}
              {% if day == 6%}
              <th class="text-uppercase align-middle">Friday</th>
              {% endif %}

              {% for item in items %}
              {% if 'const_obj' in item %}
              <td>
               
                <span class="bg-sky padding-5px-tb padding-15px-lr border-radius-5 margin-10px-bottom text-white font-size16  xs-font-size13">{{ item.const_obj.name}}</span>
              
                <div class="margin-10px-top font-size14">{{ item.const_obj.start_time | time:"H:i"}}-{{ item.const_obj.end_time  | time:"H:i"}}</div>
                
             </td>
             {%endif%}
          
             {% if 'object' in item %}
              <td>
                {% if item.object.name  == "Machine Learning"%}
                <span class="bg-purple padding-5px-tb padding-15px-lr border-radius-5 margin-10px-bottom text-white font-size16  xs-font-size13">{{item.object.name }}</span>
              
                {% elif item.object.name == "Parrallel computing" %}
                <span class="bg-yellow padding-5px-tb padding-15px-lr border-radius-5 margin-10px-bottom text-white font-size16  xs-font-size13">{{item.object.name }}</span>
                {% elif item.object.name  == "Advanced Algorithm" %}
                <span class="bg-lightred padding-5px-tb padding-15px-lr border-radius-5 margin-10px-bottom text-white font-size16  xs-font-size13">{{item.object.name }}</span>
                {% elif item.object.name  == "Compilation" %}
                <span  style='background-color: gray;' class="padding-5px-tb padding-15px-lr border-radius-5 margin-10px-bottom text-white font-size16  xs-font-size13">{{item.object.name }}</span>
               
                {% elif item.object.name  == "Compilation" %}
                <span  style='background-color: gray;' class="padding-5px-tb padding-15px-lr border-radius-5 margin-10px-bottom text-white font-size16  xs-font-size13">{{item.object.name }}</span>
               
                {% elif item.object.name  == "Game Development" %}
                <span  style='background-color: green;' class="padding-5px-tb padding-15px-lr border-radius-5 margin-10px-bottom text-white font-size16  xs-font-size13">{{item.object.name }}</span>
                {%else %}
                <span class="bg-pink padding-5px-tb padding-15px-lr border-radius-5 margin-10px-bottom text-white font-size16  xs-font-size13">{{item.object.name }}</span>
                {%endif%}
                
                <div class="margin-10px-top font-size14">{{item.object.start_time | time:"H:i"}}-{{item.object.end_time | time:"H:i"}}</div>
               
             </td>

             {% endif %}
             {% endfor %}


             
           


            </tr>
          
           
        {% endfor %}

        
            
    
    
    



                 
             
          </tbody>
      </table>
  </div>
</div>
        






     

{% endblock %}

{% block javascript %}

<script>




// Call the function to populate the timetable with the data






    $(function() {
        // Handle file selection event
        $('#fileInput').on('change', function() {
          // Get selected file name
        var fileName = $(this).val().split('\\').pop();
          // Update label text
        $(this).next('.input-group-text').html(fileName);
        $('#fileInput').css('display', 'block')
        $('#select_button').css('display','none')
        $('#convert_button').css('display','block')


        //# previewFile()
       
         

        });
    });
    
  
    
 
   
    const convert_button = document.getElementById("convert_button");

    convert_button.addEventListener("click", function() {
              
                //runProgressBar(120);

         
           
            $('#mybar_main').css('display','block')
            $('#loader-text').css('display','block')
          
            $('#fileInput').css('display', 'none')
            $('#select_button').css('display','none')
            $('#convert_button').css('display','none')

            
            var myform = document.getElementById("upload_form");
            var fd = new FormData(myform);
            var i = 0;
            move(i)

            $.ajax({
                url: "/perform_services/",
                headers: {"X-CSRFToken": '{{csrf_token}}'},
                data: fd,
                cache: false,
                processData: false,
                contentType: false,
                type: 'POST',

             
                success: function (dataofconfirm) {
                  //  move(99)
                    $('#fileInput').css('display', 'none')
                    $('#select_button').css('display','none')
                    $('#convert_button').css('display','none')
                    
                    $('#loader_container').css('display','none')
                    $('#mybar_main').css('display','none')
                    $('#loader-text').css('display','none')
                    $('#download_button').css('display','block')
                    
                    //window.location.reload()
                  
                },
                error: function (data) {
                    //document.getElementById('save').innerHTML = '';
                    $('#mybar_main').css('display','none')
                    ShowNotify('Error', data.responseJSON.error, 'error');
                }
            });
    });
   
    function move(i) {
      if (i == 0) {
        i = 1;
        var elem = document.getElementById("myBar");
        var width = 1;
        var id = setInterval(frame, 1950);
        function frame() {
          if (width >= 100) {
            clearInterval(id);
            i = 0;
          } else {
            width++;
            elem.style.width = width + "%";
          }
        }
      }
    }


    function downloadFile() {
      var title = $('#title').val();
      console.log("titler",title)
        $.ajax({ 
          url: "/download_docx/?title="+title,
          type: 'GET',
          xhrFields: {
          responseType: 'blob'
          },
          success: function(response) {
            const url = window.URL.createObjectURL(response);
            const link = document.createElement('a');
            link.href = url;
            var title = $('#title').val();
            title=title.replaceAll(" ","-");
            title='output'+title+'.docx'
            link.download =title
    
           

            // if (title.includes("Expert")) {
            //  link.download = 'output_expert_resource.docx';
            // }
            // if (title.includes("Joss")) {
            //   link.download = 'output_joss_search.docx';
            // }
            // if (title.includes("ASPION")) {
            //   link.download = 'output_aspion_search.docx';
            // }
            // if (title.includes("Clarus")) {
            //   link.download = 'output_clarus.docx';
            // }
            
            link.click();
            window.URL.revokeObjectURL(url);
            $('#select_button').css('display','block');
            $('#download_button').css('display','none');
          },
          error: function(xhr, status, error) {
            console.log("error");
          }
        });
      }


// Call the runProgressBar function with a duration of 3 minutes (180 seconds)




  
   // Example JSON data

      


        function previewFile() {
    
            const preview = document.getElementById('preview');
            const file = document.querySelector('input[type=file]').files[0];
            const reader = new FileReader();
        
            reader.addEventListener("load", function () {
              const pdfViewer = `<embed src="${reader.result}" width="500" height="600" type="application/docx">`;
              preview.innerHTML = pdfViewer;
            }, false);
        
            if (file) {
              reader.readAsDataURL(file);
            }
          }
        
        //  document.querySelector('input[type=file]').addEventListener('change', previewFile);
       


        

  
  
  
  
  
  

      

</script>
{% endblock %}