pdf/pdf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from superadmin.views import*
from django.views.static import serve 


urlpatterns = [
    
    path('login/', login_page, name='login'),
    path('', login_page),
    path('register/', register_page, name='register_page'),
    path('logout/', logout_page, name='logout'),
    path('adminn/', admin.site.urls),
    path('admin/',  include(('superadmin.urls', 'superadmin'), namespace='superadmin')),
    path('', include(('user.urls', 'user'), namespace='user')),
   
    
]
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pdf/user/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


'''
    This is url file here three url 
    one for dashboard and another one select courses
    third for view your timetable.
 
 '''
urlpatterns = [
     path('dashboard/', get_index_page, name='dashboard'), 
     path('select-courses/', select_courses, name='select_courses'),
     path('show-timetable/', show_timetable, name='show_timetable'),     
]

pdf/user/models.py
from django.db import models
from django.contrib.auth.models import User

pdf/user/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import render ,redirect
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from .serializers import  UserSerializerForTimeTable
from rest_framework.response import Response
from rest_framework import status
from django.contrib.auth.decorators import login_required

from django.db.models.functions import ExtractWeekDay
from django.db.models import Func
import datetime
from django.contrib.auth.models import User
from superadmin.models import  Allcourse, Allstudent, Constraint
import os
from  datetime import time
from itertools import groupby
from operator import itemgetter
from collections import OrderedDict
from datetime import datetime, time
import pdb

# Create your views here.
'''
    This function take three argument 
    request course for course object and constraint object 
   
    check_already_constraint
 
'''
def check_already_constraint(request,cours,constraint_obj):

    
    if cours:
        #orted_time_slots = sorted(course_list, key=lambda slot: slot['start_time'])

        if len(constraint_obj) >=2:
            print("list",constraint_obj)
            course_list = list(constraint_obj)
            time_differences = []
           
            first=constraint_obj.first()
            last = constraint_obj.last()
            if cours.start_time >=last.end_time:
                return True
            elif cours.end_time<=first.start_time:
                return True
                


            for constraint1, constraint2 in zip(course_list, course_list[1:]):   
                   
                    if constraint1.end_time <= cours.start_time <= constraint2.start_time and  constraint1.end_time <= cours.end_time <= constraint2.start_time:
                        return True
                      
                    # elif constraint1.start_time >= cours.end_time <= constraint1.end_time:
                    #     return True
                    
                    # elif len(constraint_obj) ==2:
                    #     if constraint2.end_time <= cours.start_time >= constraint2.start_time:
                    #         return True

                    
                    

            
            return False      

        elif len(constraint_obj) == 1:
            for const in constraint_obj:
               
                if const.start_time <= cours.start_time <= const.end_time or const.start_time <= cours.end_time <= const.end_time:
                    return False
                else:
                    return True
  
   

'''
    This function take five argument  and check one constraint with
    already existing constraint and courses.if any available slot for 
    constraint then constraint object is created. 
 
'''
def check_contt(request,name,day,start_time,end_time):
    days = day[:3]
    start_timee_2 = time.fromisoformat(start_time)
    end_timee_2 = time.fromisoformat(end_time)   
    allstudent=Allstudent.objects.filter(user=request.user) 
    student = Allcourse.objects.filter(allstudent__user=request.user,day=days)
    student_list=list(student)
    sorted_list = sorted(student_list, key=lambda x: x.start_time)
    first=sorted_list[0]
    last=sorted_list[len(sorted_list)-1]
    if start_timee_2 >=last.end_time:
        already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
        if already_cons:
            return False
        else:
            Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
            return True
    elif end_timee_2<=first.start_time:
        already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
        if already_cons:
            return False
        else:
            Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
            return True
    
    for constraint1, constraint2 in zip(sorted_list, sorted_list[1:]):   
            
            if constraint1.end_time <= start_timee_2 <= constraint2.start_time and  constraint1.end_time <= end_timee_2 <= constraint2.start_time:
                already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                if already_cons:
                    return False
                else:
                    Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                    return True

    return False
def check_contt_two(request,name,day,start_time,end_time):
    days = day[:3]
    start_timee_2 = time.fromisoformat(start_time)
    end_timee_2 = time.fromisoformat(end_time)   
    constraint_obj=Constraint.objects.filter(user=request.user,day=day)
    student_list=list(constraint_obj)
    sorted_list = sorted(student_list, key=lambda x: x.start_time)
    first=sorted_list[0]
    last=sorted_list[len(sorted_list)-1]
    if start_timee_2 >=last.end_time:
        already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
        if already_cons:
            return False
        else:
            Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
            return True
    elif end_timee_2<=first.start_time:
        already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
        if already_cons:
            return False
        else:
            Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
            return True
    
    for constraint1, constraint2 in zip(sorted_list, sorted_list[1:]):   
            
            if constraint1.end_time <= start_timee_2 <= constraint2.start_time and  constraint1.end_time <= end_timee_2 <= constraint2.start_time:
                already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                if already_cons:
                    return False
                else:
                    Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                    return True

    return False


def check_constraint_to_add(request,name,day,start_time,end_time):
    days = day[:3]
    start_timee_2 = time.fromisoformat(start_time)
    end_timee_2 = time.fromisoformat(end_time)
  
   
    constraint_obj=Constraint.objects.filter(user=request.user,day=day)
    allstudent=Allstudent.objects.filter(user=request.user) 
    student = Allcourse.objects.filter(allstudent__user=request.user,day=days)
    if not constraint_obj and not student:
        already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
        if already_cons:
            return False
        else:
            Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
            return True
    
    elif  constraint_obj and student:
        student_list=list(student)
        cons_list =list(constraint_obj)
        appended_list = student_list + cons_list
        sorted_list = sorted(appended_list, key=lambda x: x.start_time)
        first=sorted_list[0]
        last=sorted_list[len(sorted_list)-1]
        start_timee_2 = time.fromisoformat(start_time)
        end_timee_2 = time.fromisoformat(end_time)
        if start_timee_2 >=last.end_time:
            already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
            if already_cons:
                return False
            else:
                Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                return True
        elif end_timee_2<=first.start_time:
            already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
            if already_cons:
                return False
            else:
                Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                return True
        
        for constraint1, constraint2 in zip(sorted_list, sorted_list[1:]):   
                
                if constraint1.end_time <= start_timee_2 <= constraint2.start_time and  constraint1.end_time <= end_timee_2 <= constraint2.start_time:
                    already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                    if already_cons:
                        return False
                    else:
                        Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                        return True
    
        return False
    else:
        if student:
            student_list=list(student)
            sorted_list = sorted(student_list, key=lambda x: x.start_time)
            if len(student_list) == 1:
                first=sorted_list[0]
                if end_timee_2<=first.start_time or first.end_time <=start_timee_2:
                    already_cons=Constraint.objects.filter(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                    if already_cons:
                        return False
                    else:
                        Constraint.objects.create(user=request.user,name=name, day=day, start_time = start_time, end_time=end_time)
                        return True
            else:
                check_contt(request,name,day,start_time,end_time)

pdf/user/templates/user/layout/base.html
{% load static %}

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="icon" href="images/favicon.ico" type="image/ico"/> -->

    <title>Time Table</title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">

    <!-- bootstrap-progressbar -->
    <link href="{% static 'vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
    <!-- JQVMap -->
    <link href="{% static 'vendors/jqvmap/dist/jqvmap.min.css' %}" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">

    <link href="{% static 'vendors/pnotify/dist/pnotify.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/pnotify/dist/pnotify.buttons.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/pnotify/dist/pnotify.nonblock.css' %}" rel="stylesheet">

    <!-- jQuery custom content scroller -->
    <link href="{% static 'vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css' %}"
          rel="stylesheet"/>

    <!-- Animate.css -->
    <link href="{% static 'vendors/switchery/dist/switchery.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/animate.css/animate.min.css' %}" rel="stylesheet">
    <!-- starrr -->
    <link href="{% static 'vendors/starrr/dist/starrr.css' %}" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
    <link href="{% static 'custom_css/custom.css' %}" rel="stylesheet">


 <style>

        /* .img_height_width_header {
            width: 30% !important;
            height: 60% !important;
        } */
        body{
           
                color: #73879C;
                background: #F3F0EC;

             
                font-family: "Helvetica Neue", Roboto, Arial, "Droid Sans", sans-serif;
                font-size: 13px;
                font-weight: 400;
                line-height: 1.471;
              
           
        }
        .nav_menu{
            background: #fff;
            display:flex;
            justify-content: space-between;
          
            
        }
        .nav_left{
            width:62%;

        }
        .nav_right{
            width:28%;
            
        }
       
        #myBar {
                width: 1%;
                height: 20px;
                background-color: red;
            }
        #mybar_main {

        width: 100%;
        background-color: black;
        height:20px;
        }
        .main__container{
            width:95%;
            margin:auto;
        }
        .mycard{
            width:25%
        }
        @media only screen and (min-width: 480px) and (max-width: 768px) {
            .mycard{
            width:33%
        }
 
        }
        @media only screen and (min-width: 320px) and (max-width: 481px) {
            .mycard{
            width:100%
        }
 
        }




        body{
    margin-top:20px;
}
.bg-light-gray {
    background-color: #f7f7f7;
}
.table-bordered thead td, .table-bordered thead th {
    border-bottom-width: 2px;
}
.table thead th {
    vertical-align: bottom;
    border-bottom: 2px solid #dee2e6;
}
.table-bordered td, .table-bordered th {
    border: 1px solid #dee2e6;
}


.bg-sky.box-shadow {
    box-shadow: 0px 5px 0px 0px #00a2a7
}

.bg-orange.box-shadow {
    box-shadow: 0px 5px 0px 0px #af4305
}

.bg-green.box-shadow {
    box-shadow: 0px 5px 0px 0px #4ca520
}

.bg-yellow.box-shadow {
    box-shadow: 0px 5px 0px 0px #dcbf02
}

.bg-pink.box-shadow {
    box-shadow: 0px 5px 0px 0px #e82d8b
}

.bg-purple.box-shadow {
    box-shadow: 0px 5px 0px 0px #8343e8
}

.bg-lightred.box-shadow {
    box-shadow: 0px 5px 0px 0px #d84213
}


.bg-sky {
    background-color: #02c2c7
}

.bg-orange {
    background-color: #e95601
}

.bg-green {
    background-color: #5bbd2a
}

.bg-yellow {
    background-color: #f0d001
}

.bg-pink {
    background-color: #ff48a4
}

.bg-purple {
    background-color: #9d60ff
}

.bg-lightred {
    background-color: #ff5722
}

.padding-15px-lr {
    padding-left: 15px;
    padding-right: 15px;
}
.padding-5px-tb {
    padding-top: 5px;
    padding-bottom: 5px;
}
.margin-10px-bottom {
    margin-bottom: 10px;
}
.border-radius-5 {
    border-radius: 5px;
}

.margin-10px-top {
    margin-top: 10px;
}
.font-size14 {
    font-size: 14px;
}

.text-light-gray {
    color: #d6d5d5;
}
.font-size13 {
    font-size: 13px;
}

.table-bordered td, .table-bordered th {
    border: 1px solid #dee2e6;
}
.table td, .table th {
    padding: .75rem;
    vertical-align: top;
    border-top: 1px solid #dee2e6;
}
.form-row label {
  margin-right: 10px;
}



      
    </style> 

</head>

<body >


        <!-- top navigation -->
        {% include "user/layout/header.html" %}
        <!-- /top navigation -->
  
    
                    <!-- sidebar menu -->
              
                    <!-- /sidebar menu -->
    
            <!-- top navigation -->
        
            <!-- /top navigation -->
    
            <!-- page content -->
            {% block content %}{% endblock %}
            <!-- /page content -->
    
            <!-- footer content -->
            <br><br><br><br><br><br><br>
            {% include "user/layout/footer.html" %}
            <!--
           
           -->
  
    
<!-- jQuery -->
<script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'vendors/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
<!-- NProgress -->
<script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
<!-- Chart.js -->
<script src="{% static 'vendors/Chart.js/dist/Chart.min.js' %}"></script>
<!-- gauge.js -->
<script src="{% static 'vendors/gauge.js/dist/gauge.min.js' %}"></script>
<!-- bootstrap-progressbar -->
<script src="{% static 'vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>
<!-- Skycons -->
<script src="{% static 'vendors/skycons/skycons.js' %}"></script>
<!-- Flot -->
<script src="{% static 'vendors/Flot/jquery.flot.js' %}"></script>
<script src="{% static 'vendors/Flot/jquery.flot.pie.js' %}"></script>
<script src="{% static 'vendors/Flot/jquery.flot.time.js' %}"></script>
<script src="{% static 'vendors/Flot/jquery.flot.stack.js' %}"></script>
<script src="{% static 'vendors/Flot/jquery.flot.resize.js' %}"></script>
<!-- Flot plugins -->
<script src="{% static 'vendors/flot.orderbars/js/jquery.flot.orderBars.js' %}"></script>
<script src="{% static 'vendors/flot-spline/js/jquery.flot.spline.min.js' %}"></script>
<script src="{% static 'vendors/flot.curvedlines/curvedLines.js' %}"></script>
<!-- DateJS -->
<script src="{% static 'vendors/DateJS/build/date.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'vendors/jqvmap/dist/jquery.vmap.js' %}"></script>
<script src="{% static 'vendors/jqvmap/dist/maps/jquery.vmap.world.js' %}"></script>
<script src="{% static 'vendors/jqvmap/examples/js/jquery.vmap.sampledata.js' %}"></script>
<!-- bootstrap-daterangepicker -->
<script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>
<script src="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'vendors/switchery/dist/switchery.min.js' %}"></script>


<script src="{% static 'vendors/pnotify/dist/pnotify.js' %}"></script>
<script src="{% static 'vendors/pnotify/dist/pnotify.buttons.js' %}"></script>
<script src="{% static 'vendors/pnotify/dist/pnotify.nonblock.js' %}"></script>
<!-- Custom Theme Scripts -->
<script src="{% static 'build/js/custom.min.js' %}"></script>
<script src="{% static 'js/custom_functions.js' %}"></script>


<script type="text/javascript">


    function signup() {
       

        
        var myform = document.getElementById("upload_form");
        var fd = new FormData(myform);
        var token = '{{ csrf_token }}';
        fd.append('csrfmiddlewaretoken', token);
        $.ajax({
            url: "/register/",
            data: fd,
            cache: false,
            processData: false,
            contentType: false,
            type: 'POST',
            success: function (dataofconfirm) {
                ShowNotify('Congratulations', 'You can now login with credentials', 'success');
                $('#full_name').val('');
                $('#email').val('');
                $('#password').val('');
                $('#confirm_password').val('');
                $('#mobile').val('');
            },
            error: function (data) {
                ShowNotify('Error', data.responseJSON.error, 'error');
            }
        });
    }

    function changeStatusOfUserTrade() {
        debugger
        if ($("#Trade_cnt").is(':checked')) {
            var switchStatus = $("#Trade_cnt").is(':checked');
            $("#Trade_cnt").prop('checked', false);
            $(this).prop('checked', false);
        } else {
            var switchStatus = $("#Trade_cnt").is(':checked');
            $("#Trade_cnt").prop('checked', true);
            $(this).prop('checked', true);
        }

        var fd = new FormData();
        $.ajax({
            url: "/core/change_trade_status/",
            headers: {"X-CSRFToken": '{{csrf_token}}'},
            data: fd,
            cache: false,
            processData: false,
            contentType: false,
            type: 'POST',
            success: function (dataofconfirm) {
                ShowNotify('Congratulation', 'Trade status updated', 'success');
                window.location.reload()
            }

        });

    }

</script>

{% block javascript %}
{% endblock %}

</body>
</html>

pdf/user/templates/user/layout/footer.html
<!-- <footer>
          <div class="pull-right">
            All Rights Reserved By Machine learning One
          </div>
          <div class="clearfix"></div>
        </footer> -->
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted" style="margin-left: 0px;">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fa fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fa fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fa fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fa fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fa fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fa fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fa fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fa fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fa fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fa fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

pdf/user/templates/user/layout/header.html
<div class="top_nav">
    <div class="nav_menu">
        <div class="nav_left mt-1 ml-5"> 
            <label class="fa-2x">
                <a href="{% url 'user:dashboard' %}">
                <span class="text-light-gray " style="color: cadetblue;">TimeTable </span>
              </a>
             </label>

        </div>
        <div class="nav_right mt-1">

            {% if request.user.email %}

            <a href="{% url 'user:show_timetable' %}">
                <button type="button" class="btn btn-danger btn-lg" style="background-color: cadetblue;">View TimeTable</button>
                </a>
            <a href="{% url 'logout' %}">
                <button type="button" class="btn btn-danger btn-lg" style="background-color: cadetblue;">Logout</button>
                </a>
            
              {% else %}
              <a href="{% url 'login' %}">
                <button type="button" class="btn btn-danger btn-lg" >Login</button></a>
                <a href="{% url 'register_page' %}">
                <button type="button" class="btn btn-danger btn-lg">Signup</button>
                </a>


              {% endif %}
            

        </div>
       
      
       


      
    </div>
</div>
  
  
  
  
  

pdf/user/templates/user/layout/sidebar.html
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <ul class="nav side-menu">
            <li><a href="{% url 'core:dashboard' %}"><i class="fa fa-home"></i> Home</a></li>

            <li><a><i class="fa fa-gear"></i>Demat <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu" style="">
                    <li><a href="{% url 'core:demates' %}">Setup</a></li>
                    <li><a href="{% url 'core:demat_login' %}">Login </a></li>
                </ul>
            </li>


            <li><a><i class="fa fa-gear"></i>Portfolio <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu" style="">
                    <li><a href="{% url 'core:portfolio_management' %}">Management</a></li>
                    <li><a href="{% url 'core:live_position' %}">Live position </a></li>
                    <li><a href="{% url 'core:live_holdings' %}">Live Holdings </a></li>
                    <li><a href="{% url 'core:funds_portfolio' %}">Funds </a></li>

                </ul>
            </li>


            <li><a href="{% url 'core:change_trade_settings_page' %}"><i class="fa fa-clock-o"></i> Trade Settings</a>
            <li><a href="#"><i class="fa fa-clock-o"></i> Watch List</a>
            </li>
            <li><a href="#"><i class="fa fa-shopping-cart"></i> Orders</a>
            </li>

            <li><a href="#"><i class="fa fa-google-wallet"></i> Trades</a>
            </li>
            <li><a href="#"><i class="fa fa-line-chart"></i> Net Position</a>
            </li>


            <li><a><i class="fa fa-gear"></i>Management <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu" style="">
                    <li><a href="RiskManagement.php">Risk Management</a></li>
                    <li><a href="TimeManagement.php">Time Management</a></li>

                </ul>
            </li>

            <li><a href="#"><i class="fa fa-file"></i> Orders Logs</a></li>
            <li><a href="#"><i class="fa fa-columns"></i> Activity Logs</a></li>
            <li><a href="#"><i class="fa fa-gear"></i> Trade Settings</a></li>
            <li><a href="#"><i class="fa fa-line-chart"></i> Option Analytics</a></li>
            <li><a href="#"><i class="fa fa-wechat"></i> Broadcast Messages</a></li>
            <li><a href="#"><i class="fa fa-question"></i> Support</a></li>

        </ul>
    </div>

</div>